version: '3.8'

services:
  db:
    image: mysql:8.0.28
    environment:
      TZ: UTC
      PGTZ: UTC
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql/

  back:
    build:
      context: ./back
      args:
        WORKDIR: $WORKDIR
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./back:/$WORKDIR
      - bundle:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    tty: true
    stdin_open: true


  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    command: npm run serve

    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_PORT:$FRONT_PORT"
    depends_on:
      - back
    tty: true
    stdin_open: true


volumes:
  mysql_data:
  bundle:
